name: Test

permissions:
  packages: read

on:
  push:
    branches: ['main']
  workflow_dispatch:
  issues:
    types: [opened, edited, milestoned]

jobs:
  run-image:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest,windows-latest,macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: temurin

      - name: Display output
        run: |
          cat ~/.m2/settings.xml
        
      #- name: Setup tmate session
      #  uses: mxschmitt/action-tmate@v3
        
      - name: Run action
        id: test
        uses: gsmet/github-action-playground@main
        with:
          who-to-greet: Guillaume
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Display output
        run: |
          echo ${GITHUB_OUTPUT}
          cat ${GITHUB_OUTPUT}
      - name: Display output
        run: |
          echo "${{steps.test.outputs.testKey}}"
          echo "${{steps.test.outputs.testKey2}}"
          echo "${{join(steps.run_tests.outputs.*, '\n')}}"
