name: Test 

on:
  push:
    branches: ['main']
  workflow_dispatch:
  issues:
    types: [opened, edited, milestoned]

jobs:
  run-image:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest,windows-latest,macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: temurin

      - name: check curl in target
        run: curl -L https://${{ secrets.MAVEN_REPOSITORY_READ_TOKEN }}@maven.pkg.github.com/gsmet/github-action-playground/io/github/gsmet/github-action-playground/1.0.0-SNAPSHOT/github-action-playground-1.0.0-20220722.093742-12.jar
        shell: bash
        
      #- name: Setup tmate session
      #  uses: mxschmitt/action-tmate@v3
        
      - name: Run action
        id: test
        uses: gsmet/github-action-playground@main
        with:
          who-to-greet: Guillaume
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Display output
        run: |
          echo "${{steps.test.outputs.testKey}}"
          echo "${{steps.test.outputs.testKey2}}"
