name: Test

on:
  push:
    branches: ['main']
  workflow_dispatch:
  issues:
    types: [opened, edited, milestoned]

jobs:
  run-action:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Run action
        uses: gsmet/my-github-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
